openapi: 3.0.1
info:
  title: Сервис регистрации
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      responses:
        '200':
          description: OK
    put:
      summary: Регистрация нового пользователя.
      description: Регистрация нового пользователя.
      responses:
        '200':
          description: Пользователь зарегистрирован
    delete:
      summary: Удаление пользователья
      #operationId:
#      parameters:
#        -
      responses:
        '200':
          description: OK
    post:
      summary: Аутентификация
#      operationId:
#      parameters:
#        -
      responses:
        '200':
          description: OK