openapi: 3.0.1
info:
  title: Контент сервис
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /content:
    get:
      summary: Получение контента
      description: Получение контента
      responses:
        '200':
          description: OK
    put:
      summary: Регистрация нового пользователя.
      description: Регистрация нового пользователя.
      responses:
        '200':
          description: Пользователь зарегистрирован
    delete:
      summary: Удаление контента
      #operationId:
#      parameters:
#        -
      responses:
        '200':
          description: OK
    post:
      summary: Размещение контента
#      operationId:
#      parameters:
#        -
      responses:
        '200':
          description: OK