openapi: 3.0.1
info:
  title: Сервис оплаты
  description: API description in Markdown.
  version: 1.0.0
servers:
  - url: 'https://api.example.com'
paths:
  /payment:
    post:
      summary: Прием оплаты
      description: Прием оплаты
      responses:
        '200':
          description: OK
