apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srv2.fullname" . }}-config
  labels:
    {{- include "srv2.labels" . | nindent 4 }}
data:
  POSTGRES_DB: {{ .Values.postgress.postgres_db }}
  POSTGRES_USER: {{ .Values.postgress.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.postgress.postgres_password }}
  PGDATA: {{ .Values.postgress.pgdata }}