apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srv2.fullname" . }}
  labels:
    {{- include "srv2.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}