apiVersion: v1
kind: Secret
metadata:
  name: {{ include "srv2.fullname" . }}-secret
  labels:
    {{- include "srv2.labels" . | nindent 4 }}
type: {{ .Values.secret.type }}
data:
  username: {{ .Values.secret.username }}
  password: {{ .Values.secret.password }}
  POSTGRES_USER: {{ .Values.secret.username }}
  POSTGRES_PASSWORD: {{ .Values.secret.password }}
  spring.datasource.username: {{ .Values.secret.username }}
  spring.datasource.password: {{ .Values.secret.password }}