{
 "title": "Otus homework5",
 "description": "Otus homework5 dashboard ",
 "tags": [
  "hw5",
  "otus"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "application", "label": "Application", "query": "label_values(application)" },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{application=\"$application\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "application",
   "collapsed": true,
   "panels": [
    {
     "title": "Create User quantiles 0.5, 0.95, 0.99, max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_create_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_create_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_create_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_create_time_seconds_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Update User quantiles 0.5, 0.95, 0.99, max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_update_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_update_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_update_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_update_time_seconds_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Find User quantiles 0.5, 0.95, 0.99. max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_find_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_find_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_find_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_find_time_seconds_max", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Delete User quantiles 0.5, 0.95, 0.99, max",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "user_delete_time_seconds{quantile=\"0.5\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_delete_time_seconds{quantile=\"0.95\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "user_delete_time_seconds{quantile=\"0.99\"}",
       "legendFormat": "__auto"
      },
      { "expr": "user_delete_time_seconds_max", "legendFormat": "__auto" }
     ]
    }
   ]
  },
  { "title": "RPS & ERRORS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!~\"/actuator/prometheus|/health/\", status!=\"500\"}[1m])",
     "legendFormat": "{{method}}-{{status}}-{{uri}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "changes(http_server_requests_seconds_bucket{status=\"500\"}[1m])",
     "legendFormat": "{{ERROR}}"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "changes(user_delete_time_seconds_count{exception!=\"none\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(user_find_time_seconds_count{exception!=\"none\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(user_delete_time_seconds_count{exception!=\"none\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(user_create_time_seconds_count{exception!=\"none\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "changes(http_server_requests_seconds_bucket{status=~\"500\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status and SLA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "up{application=\"$application\",instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Up Time",
     "type": "stat",
     "gridPos": { "h": 3, "w": 5, "x": 7, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "process_uptime_seconds{application=\"$application\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Requests per second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{method}}-{{status}}-{{uri}}"
      }
     ]
    },
    {
     "title": "Response time of 0.5, 0.95, 0.99 of requests",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "95%"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "90%"
      },
      {
       "expr": "histogram_quantile(0.5, sum(rate(http_server_requests_seconds_bucket{application=\"$application\", instance=\"$instance\"}[1m])) by (le))",
       "legendFormat": "50%"
      }
     ]
    },
    {
     "title": "Mean response time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_sum{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m]) / rate(http_server_requests_seconds_count{application=\"$application\", instance=\"$instance\", uri!=\"/actuator/prometheus\"}[1m])",
       "legendFormat": "{{method}}-{{status}}-{{uri}}"
      }
     ]
    },
    {
     "title": "ERRORS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{application=\"$application\", uri!=\"/actuator/prometheus\", outcome=\"SERVER_ERROR\"}[$__rate_interval])"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  }
 ]
}