apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: srv1-ingress
  labels:
    app: srv1
spec:
  rules:
    - host: arch.homework
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: srv1-service
                port:
                  number: 8000